server:
  servlet:
    context-path: /api-email-rabbit
  port: 8084
spring:
  application:
    name: API Email Rabbit
  jpa:
    show-sql: true
  web:
    resources:
      add-mappings: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true                 
  flyway:
    url: jdbc:h2:file:./h2/api-email-rabbit;MODE=MYSQL
    user: sa
    password: 
    locations: classpath:db/migration         
  rabbitmq:
    host: 192.168.0.140
    port: 5672
    username: admin
    password: admin         
springdoc:  
  packages-to-scan: com.jetnuvem.email.api
    
logging:
  level:
    com:
      jetnuvem:
        email: DEBUG
    org:
      springframework:
        security: TRACE
management:
  metrics:
    enable:
      executor: false
  health:
    diskspace:
      enabled: false
  info:
    env:
      enabled: true
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "metrics,health,info, auditevents, loggers"
        exclude: "env"
    enabled-by-default: false
    jmx:
      exposure:
        include: "metrics"        
  endpoint:
    health:
      enabled: true    
    info:
      enabled: true
    metrics:      
      enabled: true
    loggers:
      enabled: true
    auditevents:
      enabled: true
info:
  application:
    name: ${spring.api-email-rabbit}
    descricao: API de Email
    

